# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170212_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttransaction',
            name='reference_old',
        ),
    ]
