# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_populate_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
