# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170212_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryitem',
            old_name='product',
            new_name='supplier_product',
        ),
    ]
