# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_deliveryitem_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='qty_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='The quantity in the report will be multiplied by this value.'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='received',
            field=models.BooleanField(default=False, help_text='Has the product been received?', verbose_name='☑️'),
        ),
    ]
