# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0015_auto_20170213_2104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocktakechunk',
            unique_together=set([('stocktake', 'owner')]),
        ),
    ]
