# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20170214_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_of_stock_forecast',
            field=models.DateField(blank=True, null=True),
        )
    ]
