# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20170228_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='delivers_on',
            field=models.SmallIntegerField(choices=[(0, 'MONDAY'), (1, 'TUESDAY'), (2, 'WEDNESDAY'), (3, 'THURSDAY'), (4, 'FRIDAY'), (5, 'SATURDAY'), (6, 'SUNDAY')], default=0),
            preserve_default=False,
        ),
    ]
