# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20170305_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='qty_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='The quantity in the report will be multiplied by this value.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity multiplier'),
        ),
    ]
