# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 17:18
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20151029_1047'),
    ]

    operations = [

        migrations.AddField(
            model_name='wallet',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SEK', 'Swedish Krona')], default='SEK', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
