# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 17:21
from __future__ import unicode_literals

import enum
from moneyed import Money
from django.db import migrations, models


class TrxType(enum.Enum):
    INCOMING = 0
    OUTGOING = 1


class TrxStatus(enum.Enum):
    PENDING = 0
    FINALIZED = 1
    REJECTED = 2
    CANCELED = 3


def transfer_currency(apps, schema_editor):
    Wallet = apps.get_model("wallet", "Wallet")
    WalletTrx = apps.get_model("wallet", "WalletTransaction")
    for wallet in Wallet.objects.all():
        incoming = WalletTrx.objects.filter(
            wallet=wallet.id,
            trx_status=TrxStatus.FINALIZED,
            trx_type=TrxType.INCOMING
        ).aggregate(amount=models.Sum('amount'))['amount'] or 0
        outgoing = WalletTrx.objects.filter(
            wallet=wallet.id,
            trx_status__in=[TrxStatus.PENDING, TrxStatus.FINALIZED],
            trx_type=TrxType.OUTGOING
        ).aggregate(amount=models.Sum('amount'))['amount'] or 0
        wallet.balance = Money(incoming - outgoing, wallet.currency)
        wallet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20160309_1718'),
    ]

    operations = [
        migrations.RunPython(transfer_currency)
    ]
