# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 17:21
from __future__ import unicode_literals

from moneyed import Money
from django.db import migrations, models
from wallet import enums


def transfer_currency(apps, schema_editor):
    Wallet = apps.get_model("wallet", "Wallet")
    WalletTrx = apps.get_model("wallet", "WalletTransaction")
    for wallet in Wallet.objects.all():
        incoming = WalletTrx.objects.filter(
            wallet=wallet.id,
            trx_status=enums.TrxStatus.FINALIZED,
            trx_type=enums.TrxType.INCOMING
        ).aggregate(amount=models.Sum('amount'))['amount'] or 0
        outgoing = WalletTrx.objects.filter(
            wallet=wallet.id,
            trx_status__in=[enums.TrxStatus.PENDING,
                            enums.TrxStatus.FINALIZED],
            trx_type=enums.TrxType.OUTGOING
        ).aggregate(amount=models.Sum('amount'))['amount'] or 0
        wallet.balance = Money(incoming - outgoing, wallet.currency)
        wallet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20160309_1718'),
    ]

    operations = [
        migrations.RunPython(transfer_currency)
    ]
