# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:40
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import wallet.enums


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20160309_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_status',
            field=enumfields.fields.EnumIntegerField(default=1, enum=wallet.enums.TrxStatus),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=wallet.enums.TrxType),
        ),
    ]
