# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-30 14:30
from __future__ import unicode_literals

import enum
from django.db import migrations
import enumfields.fields


class TrxType(enum.Enum):
    FINALIZED = 0
    PENDING = 1
    CANCELLATION = 2


class TrxStatus(enum.Enum):
    PENDING = 0
    FINALIZED = 1
    REJECTED = 2
    CANCELED = 3


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20160309_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_status',
            field=enumfields.fields.EnumIntegerField(default=1, enum=TrxStatus),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=TrxType),
        ),
    ]
