# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20170130_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='internal_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.WalletTransaction'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='date created'),
        ),
    ]
