# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 22:58
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import enumfields.fields
import wallet.enums
import enum


class TrxType(enum.Enum):
    FINALIZED = 0
    PENDING = 1
    CANCELLATION = 2


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_auto_20170218_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), help_text='Positive amount to deposit money. Negative amount to withdraw money.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='trx_type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=TrxType, verbose_name='type'),
        ),
    ]
