# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:35
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import wallet.enums


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20170312_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='internal_reference',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='trx_type',
        ),
        migrations.AlterField(
            model_name='wallettransactionstatus',
            name='status',
            field=enumfields.fields.EnumIntegerField(default=1, enum=wallet.enums.TrxStatus, verbose_name='type'),
        ),
    ]
