# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 22:04
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foobar', '0008_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SEK', 'Swedish Krona')], default='SEK', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
    ]
