# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 22:06
from __future__ import unicode_literals

from django.db import migrations
from moneyed import Money


def update_amounts(apps, schema_editor):
    Purchase = apps.get_model("foobar", "Purchase")
    PurchaseItem = apps.get_model("foobar", "PurchaseItem")
    for p in Purchase.objects.all():
        qs = PurchaseItem.objects.filter(purchase=p)
        p.amount = sum((i.amount * i.qty for i in qs), Money(0, 'SEK'))
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foobar', '0009_auto_20160309_2204'),
    ]

    operations = [
        migrations.RunPython(update_amounts)
    ]
