# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foobar', '0010_auto_20160309_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foobar.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
