# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foobar', '0012_auto_20160829_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='card_id',
        ),
    ]
