# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 12:24
from __future__ import unicode_literals

from django.db import migrations
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('foobar', '0014_card_date_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=utils.models.ScannerField(max_length=20, unique=True),
        ),
    ]
