# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 21:54
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType


def migrate_references(apps, schema_editor):
    ProductTransaction = apps.get_model("shop", "ProductTransaction")
    PurchaseItem = apps.get_model("foobar", "PurchaseItem")
    ContentType = apps.get_model("contenttypes", "ContentType")
    trxs = ProductTransaction.objects.all()
    for trx in trxs:
        if trx.reference_old:
            item_obj = PurchaseItem.objects.get(id=trx.reference_old)
            trx.reference_ct = ContentType.objects.get_for_model(item_obj)
            trx.reference_id = item_obj.id
            trx.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foobar', '0015_auto_20160919_1224'),
        ('shop', '0007_auto_20170212_0932'),
        ('contenttypes', '__first__'),
    ]

    operations = [
        migrations.RunPython(migrate_references),
    ]
