# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foobar', '0021_auto_20170330_0916'),
        ('foobar', '0021_auto_20170313_2018'),
    ]

    operations = [
    ]
