# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foobar', '0022_merge_20170412_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date_created'], 'permissions': (('can_take_card_payments', 'Can take card payments'),)},
        ),
    ]
